config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pictures#home'
  resources 'pictures' do
  	put :up
  	put :down
  end
  resources :payments
  get 'admin/view' => 'admin#view'
  resources 'authors'
  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'
end

app/models/author.rb
class Author < ActiveRecord::Base
	validates :name, presence: true, uniqueness: true
end

app/models/picture.rb
class Picture < ActiveRecord::Base
	belongs_to :user
	validates :title, :url, :description, :user_id, :score, presence: true
	default_scope { order(score: :desc) }

	def vote i
		self.score += i
		self.save
	end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :pictures
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	def view
		@pictures = Picture.all
		@authors = Author.all
		@users = User.all
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
	def index
		@authors = Author.all
    @users = User.all
	end

  def show
  	@author = Author.find(params[:id])
    @user = User.find(params[:id])
    @userpics = @user.pictures
  end

  def up
    @picture = Picture.find(params[:picture_id])
    @picture.score += 1
    if @picture.save
      redirect_to show_path(article.id)
    else
      puts "ERROR: Your vote was not counted"
    end
  end

  def down
    @picture = Picture.find(params[:picture_id])
    @picture.score += -1
    if @picture.save
      redirect_to show_path
    else
      puts "ERROR: Your vote was not counted"
    end
  end

  def new
    @author = Author.new
    @picture = Picture.new
  end

  def create
    @author = Author.new(author_params)
    @author.save
  end

  def destroy
    @author = Author.find(params[:id])
    if @author.destroy
      flash[:notice] = "You deleted this post :("
      redirect_to authors_path
    end
  end

  def edit
    @author = Author.find(params[:id])
  end

  def update
    @author = Author.find(params[:id])
    @author.update(author_params)
    redirect_to author_path
  end

private
  def author_params
    params.require(:author).permit(:name)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
	def index
		@pictures = Picture.all
	end

  def up
    @picture = Picture.find(params[:picture_id])
    if @picture.vote 1
      redirect_to pictures_path
    else
      puts "ERROR: Your vote was not counted"
    end
  end

  def down
    @picture = Picture.find(params[:picture_id])
    if @picture.vote -1
      redirect_to pictures_path
    else
      puts "ERROR: Your vote was not counted"
    end
  end

  def home
    @pictures = Picture.all
    @urls = []
    @pictures.each do |pic|
      @urls << pic.url
    end
  end

  def show
  	@picture = Picture.find(params[:id])
  end

  def new
		authenticate_user!
    @picture = Picture.new
  end

  def create
    @picture = Picture.new(picture_params)
		@picture.user_id = current_user.id
    if @picture.save
      redirect_to picture_path(@picture)
    else
      render "new"
    end
  end

  def destroy
    @picture = Picture.find(params[:id])
    if @picture.destroy
      flash[:notice] = "You deleted this post :("
      redirect_to pictures_path
    end
  end

  def edit
    @picture = Picture.find(params[:id])
  end

  def update
    @picture = Picture.find(params[:id])
    @picture.update(picture_params)
    redirect_to picture_path
  end

private
  def picture_params
    params.require(:picture).permit(:url, :title, :description, :user_id, :score)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/view.slim
h1.info Update Users
.info.top
	- @users.each do |user|
		h3 = user.email
		p = link_to "edit", edit_user_registration_path(user.id)
		p = link_to "delete", cancel_user_registration_path(user.id)
h1.info Update Pictures
- @pictures.each do |pic|
	img src=pic.url
	p.info = pic.title
	p.info = pic.description
	p.info-italic = pic.user.email
	p.info = link_to "Edit", edit_picture_path(pic.id)
	p.info = link_to "Delete", picture_path(pic.id), method: :delete

app/views/application/_index.slim
header.centered-navigation[role="banner"]
  .centered-navigation-wrapper
    a.mobile-logo[href="javascript:void(0)"]
      img[src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_logo_3_dark.png" alt="Logo image"]
    a#js-centered-navigation-mobile-menu.centered-navigation-mobile-menu[href="javascript:void(0)"]
      | MENU
    nav[role="navigation"]
      ul#js-centered-navigation-menu.centered-navigation-menu.show
        li.nav-link
          a[href="javascript:void(0)"]
            | Products
        li.nav-link
          a[href="javascript:void(0)"]
            | About Us
        li.nav-link
          a[href="javascript:void(0)"]
            | Contact
        li.nav-link.logo
          a.logo[href="javascript:void(0)"]
            img[src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_logo_3_dark.png" alt="Logo image"]
        li.nav-link
          a[href="javascript:void(0)"]
            | Testimonials
        li.nav-link.more
          a[href="javascript:void(0)"]
            | More
          ul.submenu
            li
              a[href="javascript:void(0)"]
                | Submenu Item
            li
              a[href="javascript:void(0)"]
                | Another Item
            li.more
              a[href="javascript:void(0)"]
                | Item with submenu
              ul.submenu
                li
                  a[href="javascript:void(0)"]
                    | Sub-submenu Item
                li
                  a[href="javascript:void(0)"]
                    | Another Item
            li.more
              a[href="javascript:void(0)"]
                | Another submenu
              ul.submenu
                li
                  a[href="javascript:void(0)"]
                    | Sub-submenu
                li
                  a[href="javascript:void(0)"]
                    | An Item
        li.nav-link
          a[href="javascript:void(0)"]
            | Sign up

app/views/application/_nav.slim
header.centered-navigation[role="banner"]
  .centered-navigation-wrapper
    = link_to image_tag("https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_logo_3_dark.png"), root_path, class: "mobile-logo"
    a#js-centered-navigation-mobile-menu.centered-navigation-mobile-menu[href="javascript:void(0)"]
      | MENU
    nav[role="navigation"]
      ul#js-centered-navigation-menu.centered-navigation-menu.show
        li.nav-link
          = link_to "Pictures", pictures_path
        li.nav-link
          = link_to "Authors", authors_path
        li.nav-link.logo
          a.logo = link_to root_path
            img[src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_logo_3_dark.png" alt="Logo image"]
        - if signed_in?
          li.nav-link = link_to "New Picture", new_picture_path 
          li.nav-link = link_to "Log Out", destroy_user_session_path, method: :delete
        - else
          li.nav-link = link_to 'Sign Up', new_user_registration_path
          li.nav-link = link_to 'Log In', new_user_session_path
        -if current_user && current_user.admin?
          li.nav-link = link_to "Admin", admin_view_path

app/views/authors/_form.slim
= simple_form_for @author do |a|
	= a.input :name
	= a.button :submit

app/views/authors/index.slim
.authors-container
	- @users.each do |user|
		p
			= link_to "Click to see #{user.email}'s pictures! They have #{user.pictures.count} pictures", author_path(user.id)

app/views/authors/new.slim
= simple_form_for @author do |f|
	= f.input :name
	= f.button :submit

app/views/authors/show.slim
- @userpics.each do |pic|
	.hover-tile-outer style="background-image:url(#{pic.url}); background-repeat:no-repeat; background-size: 100% 100%;"
		.hover-tile-container
			.hover-tile.hover-tile-visible
			.hover-tile.hover-tile-hidden
				h4
				  = pic.title
				p.picture-score
					| Votes : 
					= pic.score
				.up-vote
					= button_to "Up Vote", picture_up_path(pic.id), 	method: :put
				.down-vote
					= button_to "Down vote", picture_down_path(pic.id), method: :put
				p
				  = pic.description
				p.author-name
					| Author ~
					= pic.user.email

app/views/form/_form.html.erb
<%= form_for :article do |f| %>
  <p> 
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Office
    meta name="viewport" content="width=device-width, initial-scale=1"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
 	= render 'nav'
  = yield

app/views/pictures/_form.slim
.form-container
	= simple_form_for @picture do |f|
	  = f.input :url
	  = f.input :title
	  = f.input :description, as: :text
	  = f.button :submit

app/views/pictures/edit.slim
= render 'form'

app/views/pictures/home.slim
.logo-header
	img.home-pic src="http://images.fanpop.com/images/image_uploads/Dunder-Mifflin-Logo-the-office--28us-29-41129_1024_768.jpg"

	h1.prompt This site is all about The Office!
	p.info Please only upload pictures of, or relating to, The Office.
= render 'refills/griditems', urls: @urls

.button-container
	button.home-link
		= link_to "Add to the awesomeness!", new_picture_path

app/views/pictures/index.slim
= render 'refills/hovertile'

.home-button
	button.home-link
		= link_to "Home", root_path

app/views/pictures/show.slim
p.pic-title
	= @picture.title
img	src=@picture.url
- if signed_in? && current_user.admin?
	= link_to "Edit", edit_picture_path(@picture)
	= link_to "Delete", picture_path(@picture), method: :delete
p.pic-description
	= @picture.description

app/views/refills/_griditems.slim
.grid-items
  a.grid-item[href="javascript:void(0)"]
    img[src=urls[0] alt=""]
  	h1 1st
  a.grid-item.grid-item-big.grid-item-image[href="javascript:void(0)"]
    img[src=urls[1] alt=""]
  	h1	2nd
  a.grid-item.grid-item-big[href="javascript:void(0)"]
    img[src=urls[2] alt=""]
  	h1 3rd
  a.grid-item[href="javascript:void(0)"]
    img[src=urls[3] alt=""]
  	h1 4th
  a.grid-item[href="javascript:void(0)"]
    img[src=urls[4] alt=""]
  	h1 5th
  a.grid-item.grid-item-big[href="javascript:void(0)"]
    img[src=urls[5] alt=""]
  	h1 6th

app/views/refills/_hovertile.slim
- @pictures.each do |pic|
	.hover-tile-outer style="background-image:url(#{pic.url}); background-repeat:no-repeat; background-size: 100% 100%;"
		.hover-tile-container
			.hover-tile.hover-tile-visible
			.hover-tile.hover-tile-hidden
				h4
				  = pic.title
				p.picture-score
					| Votes : 
					= pic.score
				.up-vote
					= button_to "Up Vote", picture_up_path(pic.id), 	method: :put
				.down-vote
					= button_to "Down vote", picture_down_path(pic.id), method: :put
				p
				  = pic.description
				= link_to "Click to see picture", picture_path(pic.id)